on:
  push:
    branches:
      - 'main'
  schedule:
  - cron: "0 10 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install OS dependencies
        run: sudo apt install ffmpeg

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run python script
        run: python terminal.py
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}

      - name: Update to git
        run: |
          git config --global user.name 'Salledelavage'
          git config --global user.email 'salledelavager@gmail.com'
          git add --all
          git commit -m "Updating Readme on: ${TIME}"
          git push
