on:
  # push:
  #   branches:
  #     - 'main'
  #     - 'dev'
  schedule:
  - cron: "0 10 * * 5"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install OS dependencies
        run: sudo apt install ffmpeg

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run python script
        run: python terminal.py
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+05:00"

      - name: Update to git
        run: |
          git config --global user.name 'Salledelavage'
          git config --global user.email 'salledelavager@gmail.com'
          git add --all
          git commit -m "Updating Readme on: $R_TIME"
          git push
        env:
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
